language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
  
env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.2.5 WP_MULTISITE=0
    - WP_VERSION=4.2.5 WP_MULTISITE=1
matrix:
    include:
       - php: 5.3
         env: WP_VERSION=latest WP_MULTISITE=0 TEST_GROUP=--group=uninstall
       - php: 5.3
         env: WP_VERSION=latest WP_MULTISITE=1 TEST_GROUP=--group=uninstall
       - php: 5.6
         env: WP_VERSION=latest WP_MULTISITE=0 TEST_GROUP=--group=uninstall
       - php: 5.6
         env: WP_VERSION=latest WP_MULTISITE=1 TEST_GROUP=--group=uninstall
before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit $TEST_GROUP